- name: Deploy RKE2
  hosts: all
  become: yes
  vars:
    rke2_ha_mode: false
    rke2_server_taint: true
    rke2_download_kubeconf: true
    rke2_token: 
  vars_files:
    - ../vars/main.yml
  roles:
     - role: lablabs.rke2
